# Generated by Django 3.1.5 on 2021-08-24 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
