# Generated by Django 3.1.5 on 2021-08-16 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tier', '0001_initial'),
    ]

    operations = [
    ]
