# Generated by Django 3.1.5 on 2021-08-20 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tier', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tier',
            name='number',
        ),
        migrations.RemoveField(
            model_name='tier',
            name='user',
        ),
    ]
