# Generated by Django 3.1.5 on 2021-08-20 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tier', '0002_auto_20210820_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='tier',
        ),
        migrations.DeleteModel(
            name='Tier',
        ),
    ]
