# Generated by Django 3.1.5 on 2021-08-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tier', '0003_auto_20210820_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expired',
            field=models.BooleanField(default=True),
        ),
    ]
