# Generated by Django 3.1.5 on 2021-08-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0006_peoplelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
